### ISSUE TITLE
Is there any options to set default image like dropify

### ISSUE THREAD

**Issue by ManiruzzamanAkash** [khofaai/vue-dropify#15]
Hei,
Is there any options how to use default image here. 
Like in dropify.js there is a option to set default file using `data-default-file`.

```html
<input type="file" class="dropify" data-default-file="url_of_your_file" />
```

I've tried with this - 
```js
<vue-dropify
      v-model="imageValue"
      @change="changeImage"
      :data-default-file="imageValue"
/>
```

But it's not working..? 

Will I create a PR or it already exist in another way ??

**Comment by khofaai** [comment]
Hi, yes there is, my bad i didn't document it, 
you can add `src` attribute with `base64` image for example,

**Comment by ManiruzzamanAkash** [comment]
Thanks yes, It works with `:src`
```js
<vue-dropify
      v-model="imageValue"
      @change="changeImage"
      :src="imageValue"
/>
```

Thanks @khofaai
