### ISSUE TITLE
The multiple option 

### ISSUE THREAD

**Issue by pickkck** [khofaai/vue-dropify#16]
Hi, i have a problem when i try to use the multiple option, i selected two images and when i do a console.log this print a array with length 2, one of the elements its ok cause i recived a image in base64, but the other one is just an object with no value 
![Captura de Pantalla 2021-07-07 a la(s) 16 20 27](https://user-images.githubusercontent.com/28303598/124830295-47795600-df3f-11eb-85b1-62066d02d365.png)
If you have any solution, tankhs a lot

**Comment by khofaai** [comment]
Hi @pickkck, i'll check that as soon as i can, 
Thank you for sharing the problem !

**Comment by khofaai** [comment]
@pickkck: the fix has been merged in #17, now you will get all images as `File` instance,
