### ISSUE TITLE
removeImageAll() not working

### ISSUE THREAD

**Issue by VictorFer25** [khofaai/vue-dropify#7]
If I try to put this. $ Refs.image.removeImageAll () it doesn't remove the image

**Comment by khofaai** [comment]
Alright, i'll check that. thanks

**Comment by khofaai** [comment]
it appear that i didn't have the issue, can you show me your code ? also if you're interessted i've just added `v-model` support to `v0.6.0` if that solve your issue,
thanks

**Comment by VictorFer25** [comment]
Well, it seems that it already worked, I do not know that the truth will change, but thanks I will check the v-model
